### ISSUE TITLE
Create shared `Popover` component

### ISSUE THREAD

**Issue by kanta1207** [genesis-tech-tribe/nishiki-frontend#198]
## Description
Create shared `Popover` component based on shadcnUI and RadixUI
⏬ Example usage (in group single page)
![Image](https://github.com/genesis-tech-tribe/nishiki-frontend/assets/99339182/4fc8d9fe-196b-4010-82ca-d7a14c8d52a1)

**Comment by uskayyyyy** [comment]
Dupe #192
